language: php

php:
  - 5.6
  - hhvm
  - 7.0

matrix:
    allow_failures:
        - php: hhvm
        - php: 7.0

before_install:
  - pip install --user codecov

before_script: composer install
script: phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
